In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
customers=pd.read_csv("Customers.csv")
products=pd.read_csv("Products.csv")
transections=pd.read_csv("Transactions.csv")

In [3]:
customers.head()

  CustomerID        CustomerName         Region  SignupDate
0      C0001    Lawrence Carroll  South America  2022-07-10
1      C0002      Elizabeth Lutz           Asia  2022-02-13
2      C0003      Michael Rivera  South America  2024-03-07
3      C0004  Kathleen Rodriguez  South America  2022-10-09
4      C0005         Laura Weber           Asia  2022-08-15

In [4]:
products.head()

  ProductID              ProductName     Category   Price
0      P001     ActiveWear Biography        Books  169.30
1      P002    ActiveWear Smartwatch  Electronics  346.30
2      P003  ComfortLiving Biography        Books   44.12
3      P004            BookWorld Rug   Home Decor   95.69
4      P005          TechPro T-Shirt     Clothing  429.31

In [5]:
transections.head()

,TransactionID,CustomerID,ProductID,TransactionDate,Quantity,TotalValue,Price
0,T00001,C0199,P067,2024-08-25 12:38:23,1,300.68,300.68
1,T00112,C0146,P067,2024-05-27 22:23:54,1,300.68,300.68
2,T00166,C0127,P067,2024-04-25 07:38:55,1,300.68,300.68
3,T00272,C0087,P067,2024-03-26 22:55:37,2,601.36,300.68
4,T00363,C0070,P067,2024-03-21 15:10:10,3,902.04,300.68

In [6]:
final_df=products.merge(transections,on="ProductID").merge(customers,on="CustomerID")

In [7]:
final_df

,ProductID,ProductName,Category,Price_x,TransactionID,CustomerID,TransactionDate,Quantity,TotalValue,Price_y,CustomerName,Region,SignupDate
0,P001,ActiveWear Biography,Books,169.30,T00088,C0019,2024-01-30 17:23:03,2,338.60,169.30,Brandon Rodriguez,Europe,2023-01-12
1,P001,ActiveWear Biography,Books,169.30,T00314,C0024,2024-09-24 17:15:16,4,677.20,169.30,Michele Cooley,North America,2024-02-05
2,P001,ActiveWear Biography,Books,169.30,T00428,C0071,2024-08-02 08:13:23,2,338.60,169.30,Taylor Murphy,South America,2022-07-01
3,P001,ActiveWear Biography,Books,169.30,T00433,C0036,2024-05-05 05:01:18,2,338.60,169.30,Brian Aguilar DDS,North America,2024-07-06
4,P001,ActiveWear Biography,Books,169.30,T00449,C0191,2024-12-12 12:17:38,1,169.30,169.30,Samantha Gibson DVM,South America,2024-04-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,P100,HomeSense Sweater,Clothing,126.34,T00115,C0161,2024-03-10 02:22:50,1,126.34,126.34,Jessica Warren,Asia,2022-03-14
996,P100,HomeSense Sweater,Clothing,126.34,T00283,C0109,2024-07-16 14:50:07,4,505.36,126.34,Abigail Jones,North America,2022-05-09
997,P100,HomeSense Sweater,Clothing,126.34,T00301,C0109,2024-07-13 08:15:45,2,252.68,126.34,Abigail Jones,North America,2022-05-09
998,P100,HomeSense Sweater,Clothing,126.34,T00740,C0156,2024-08-24 19:10:31,4,505.36,126.34,William Adams,North America,2023-08-19
999,P100,HomeSense Sweater,Clothing,126.34,T00820,C0077,2024-03-11 10:55:51,2,252.68,126.34,Scott Sims,South America,2023-10-18

In [8]:
final_df['Price_x']==final_df['Price_y']

0      True
1      True
2      True
3      True
4      True
       ...
995    True
996    True
997    True
998    True
999    True
Length: 1000, dtype: bool

In [9]:
df=final_df.drop(columns="Price_x").rename(columns={"Price_y":"Price"})

In [10]:
df

,ProductID,ProductName,Category,TransactionID,CustomerID,TransactionDate,Quantity,TotalValue,Price,CustomerName,Region,SignupDate
0,P001,ActiveWear Biography,Books,T00088,C0019,2024-01-30 17:23:03,2,338.60,169.30,Brandon Rodriguez,Europe,2023-01-12
1,P001,ActiveWear Biography,Books,T00314,C0024,2024-09-24 17:15:16,4,677.20,169.30,Michele Cooley,North America,2024-02-05
2,P001,ActiveWear Biography,Books,T00428,C0071,2024-08-02 08:13:23,2,338.60,169.30,Taylor Murphy,South America,2022-07-01
3,P001,ActiveWear Biography,Books,T00433,C0036,2024-05-05 05:01:18,2,338.60,169.30,Brian Aguilar DDS,North America,2024-07-06
4,P001,ActiveWear Biography,Books,T00449,C0191,2024-12-12 12:17:38,1,169.30,169.30,Samantha Gibson DVM,South America,2024-04-07
...,...,...,...,...,...,...,...,...,...,...,...,...
995,P100,HomeSense Sweater,Clothing,T00115,C0161,2024-03-10 02:22:50,1,126.34,126.34,Jessica Warren,Asia,2022-03-14
996,P100,HomeSense Sweater,Clothing,T00283,C0109,2024-07-16 14:50:07,4,505.36,126.34,Abigail Jones,North America,2022-05-09
997,P100,HomeSense Sweater,Clothing,T00301,C0109,2024-07-13 08:15:45,2,252.68,126.34,Abigail Jones,North America,2022-05-09
998,P100,HomeSense Sweater,Clothing,T00740,C0156,2024-08-24 19:10:31,4,505.36,126.34,William Adams,North America,2023-08-19
999,P100,HomeSense Sweater,Clothing,T00820,C0077,2024-03-11 10:55:51,2,252.68,126.34,Scott Sims,South America,2023-10-18

In [11]:
df.isna().sum()

ProductID          0
ProductName        0
Category           0
TransactionID      0
CustomerID         0
TransactionDate    0
Quantity           0
TotalValue         0
Price              0
CustomerName       0
Region             0
SignupDate         0
dtype: int64

In [12]:
df.duplicated().sum()

0

In [13]:
df['TransactionDate']=pd.to_datetime(df['TransactionDate'])

In [14]:
df['SignupDate']=pd.to_datetime(df['SignupDate'])

In [15]:
df.head()

,ProductID,ProductName,Category,TransactionID,CustomerID,TransactionDate,Quantity,TotalValue,Price,CustomerName,Region,SignupDate
0,P001,ActiveWear Biography,Books,T00088,C0019,2024-01-30 17:23:03,2,338.6,169.3,Brandon Rodriguez,Europe,2023-01-12
1,P001,ActiveWear Biography,Books,T00314,C0024,2024-09-24 17:15:16,4,677.2,169.3,Michele Cooley,North America,2024-02-05
2,P001,ActiveWear Biography,Books,T00428,C0071,2024-08-02 08:13:23,2,338.6,169.3,Taylor Murphy,South America,2022-07-01
3,P001,ActiveWear Biography,Books,T00433,C0036,2024-05-05 05:01:18,2,338.6,169.3,Brian Aguilar DDS,North America,2024-07-06
4,P001,ActiveWear Biography,Books,T00449,C0191,2024-12-12 12:17:38,1,169.3,169.3,Samantha Gibson DVM,South America,2024-04-07

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ProductID        1000 non-null   object
 1   ProductName      1000 non-null   object
 2   Category         1000 non-null   object
 3   TransactionID    1000 non-null   object
 4   CustomerID       1000 non-null   object
 5   TransactionDate  1000 non-null   datetime64[ns]
 6   Quantity         1000 non-null   int64
 7   TotalValue       1000 non-null   float64
 8   Price            1000 non-null   float64
 9   CustomerName     1000 non-null   object
 10  Region           1000 non-null   object
 11  SignupDate       1000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(1), object(7)
memory usage: 93.9+ KB

In [17]:
df.columns

Index(['ProductID', 'ProductName', 'Category', 'TransactionID', 'CustomerID',
       'TransactionDate', 'Quantity', 'TotalValue', 'Price', 'CustomerName',
       'Region', 'SignupDate'],
      dtype='object')

# Feature Engineering

In [18]:
customer_features = df.groupby('CustomerID').agg({
    'TransactionID': 'count',       # Total transactions
    'Quantity': 'sum',              # Total quantity purchased
    'TotalValue': ['sum', 'mean'],  # Total and average transaction value
    'Category': lambda x: len(set(x)),  # Number of unique product categories
}).reset_index()

In [19]:
customer_features

    CustomerID TransactionID Quantity TotalValue              Category
                       count      sum        sum         mean <lambda>
0        C0001             5       12    3354.52   670.904000        3
1        C0002             4       10    1862.74   465.685000        2
2        C0003             4       14    2725.38   681.345000        3
3        C0004             8       23    5354.88   669.360000        3
4        C0005             3        7    2034.24   678.080000        2
..         ...           ...      ...        ...          ...      ...
194      C0196             4       12    4982.88  1245.720000        3
195      C0197             3        9    1928.65   642.883333        2
196      C0198             2        3     931.83   465.915000        2
197      C0199             4        9    1979.28   494.820000        2
198      C0200             5       16    4758.60   951.720000        4

[199 rows x 6 columns]

In [20]:
customer_features.columns

MultiIndex([(   'CustomerID',         ''),
            ('TransactionID',    'count'),
            (     'Quantity',      'sum'),
            (   'TotalValue',      'sum'),
            (   'TotalValue',     'mean'),
            (     'Category', '<lambda>')],
           )

In [21]:
customer_features.columns = ['CustomerID', 'TotalTransactions', 'TotalQuantity', 
                             'TotalValue', 'AvgTransactionValue', 'UniqueCategories']

In [22]:
customer_features

,CustomerID,TotalTransactions,TotalQuantity,TotalValue,AvgTransactionValue,UniqueCategories
0,C0001,5,12,3354.52,670.904000,3
1,C0002,4,10,1862.74,465.685000,2
2,C0003,4,14,2725.38,681.345000,3
3,C0004,8,23,5354.88,669.360000,3
4,C0005,3,7,2034.24,678.080000,2
...,...,...,...,...,...,...
194,C0196,4,12,4982.88,1245.720000,3
195,C0197,3,9,1928.65,642.883333,2
196,C0198,2,3,931.83,465.915000,2
197,C0199,4,9,1979.28,494.820000,2
198,C0200,5,16,4758.60,951.720000,4

In [23]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /Users/tusharbuttan/miniconda3/lib/python3.10/site-packages (1.6.1)
Requirement already satisfied: scipy>=1.6.0 in /Users/tusharbuttan/miniconda3/lib/python3.10/site-packages (from scikit-learn) (1.15.1)
Requirement already satisfied: joblib>=1.2.0 in /Users/tusharbuttan/miniconda3/lib/python3.10/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/tusharbuttan/miniconda3/lib/python3.10/site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: numpy>=1.19.5 in /Users/tusharbuttan/miniconda3/lib/python3.10/site-packages (from scikit-learn) (1.24.3)

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
sc=StandardScaler()

In [26]:
scaled=sc.fit_transform(customer_features.iloc[:,1:])

In [27]:
scaled

array([[-1.14581896e-02, -1.22032964e-01, -6.17014282e-02,
        -7.02634115e-02,  1.60540325e-01],
       [-4.67494136e-01, -4.48000209e-01, -8.77743532e-01,
        -9.34932971e-01, -9.04377163e-01],
       [-4.67494136e-01,  2.03934282e-01, -4.05857221e-01,
        -2.62713110e-02,  1.60540325e-01],
       [ 1.35664965e+00,  1.67078689e+00,  1.03254704e+00,
        -7.67688998e-02,  1.60540325e-01],
       [-9.23530083e-01, -9.36951078e-01, -7.83928612e-01,
        -4.00280592e-02, -9.04377163e-01],
       [-4.67494136e-01, -1.22032964e-01,  4.15879421e-01,
         1.55606020e+00,  1.60540325e-01],
       [-9.23530083e-01, -7.73967455e-01, -4.85482293e-01,
         7.26220709e-01, -9.04377163e-01],
       [ 2.26872154e+00,  1.18183602e+00,  4.39970436e-01,
        -1.09724996e+00,  1.22545781e+00],
       [-9.23530083e-01, -1.58888557e+00, -1.40630171e+00,
        -1.63794564e+00, -9.04377163e-01],
       [-4.67494136e-01, -1.22032964e-01, -9.57166204e-01,
        -1.08786883e+00, -9.04377163e-01],
       [-1.14581896e-02,  4.09506590e-02,  1.43695808e-01,
         2.46146011e-01,  1.60540325e-01],
       [ 9.00613703e-01,  1.01885240e+00,  9.64923716e-01,
         2.51719736e-01,  1.60540325e-01],
       [ 9.00613703e-01,  8.55868773e-01,  1.38575064e+00,
         7.14772302e-01,  1.60540325e-01],
       [-1.83560198e+00, -1.75186919e+00, -1.72239508e+00,
        -1.55440798e+00, -1.96929465e+00],
       [-1.37956603e+00, -1.42590195e+00, -1.26353893e+00,
        -4.58587130e-01, -9.04377163e-01],
       [-1.14581896e-02, -4.48000209e-01,  2.22697270e-01,
         3.67845832e-01,  1.60540325e-01],
       [ 1.35664965e+00,  1.34481964e+00,  7.03751732e-01,
        -3.93332111e-01,  1.22545781e+00],
       [-1.14581896e-02,  8.55868773e-01,  7.19084865e-01,
         1.13251879e+00,  1.60540325e-01],
       [ 4.44577757e-01, -2.85016587e-01, -7.01010446e-01,
        -1.36209440e+00, -9.04377163e-01],
       [-1.83560198e+00, -1.58888557e+00, -1.39212827e+00,
         9.89431754e-01, -1.96929465e+00],
       [ 1.35664965e+00,  6.92885150e-01,  1.06812560e+00,
        -4.25139647e-02,  1.22545781e+00],
       [ 4.44577757e-01,  3.66917905e-01,  6.49732938e-01,
         3.71894908e-01,  1.22545781e+00],
       [ 4.44577757e-01,  2.03934282e-01,  9.25204175e-01,
         7.25525498e-01, -9.04377163e-01],
       [ 9.00613703e-01,  2.03934282e-01,  8.73630943e-02,
        -7.13895042e-01,  1.22545781e+00],
       [-4.67494136e-01, -7.73967455e-01, -1.02704328e+00,
        -1.22242373e+00,  1.60540325e-01],
       [-4.67494136e-01, -1.22032964e-01,  4.47114950e-02,
         8.41341307e-01,  1.60540325e-01],
       [-4.67494136e-01, -1.22032964e-01, -4.94716088e-01,
        -1.97377450e-01,  1.60540325e-01],
       [ 1.35664965e+00,  1.83377051e+00,  1.83377022e+00,
         6.94646549e-01,  1.22545781e+00],
       [-4.67494136e-01, -4.48000209e-01, -9.19793403e-01,
        -1.01590397e+00,  1.60540325e-01],
       [-1.14581896e-02,  4.09506590e-02, -5.01969649e-01,
        -7.48485845e-01,  1.60540325e-01],
       [-4.67494136e-01, -4.48000209e-01, -7.99715776e-01,
        -7.84683157e-01,  1.60540325e-01],
       [-9.23530083e-01, -1.26291832e+00, -1.52856197e+00,
        -1.95184388e+00,  1.60540325e-01],
       [-1.83560198e+00, -1.75186919e+00, -1.82415282e+00,
        -2.33818449e+00, -1.96929465e+00],
       [ 4.44577757e-01,  6.92885150e-01, -2.15590718e-01,
        -7.38946709e-01,  1.60540325e-01],
       [-4.67494136e-01, -4.48000209e-01, -4.81220962e-01,
        -1.71391311e-01,  1.60540325e-01],
       [-9.23530083e-01, -7.73967455e-01, -8.69417800e-01,
        -2.59518065e-01,  1.60540325e-01],
       [-1.14581896e-02,  2.03934282e-01,  4.29664470e-01,
         6.86673745e-01, -9.04377163e-01],
       [-1.14581896e-02,  4.09506590e-02, -4.21463867e-01,
        -6.24468655e-01, -9.04377163e-01],
       [ 4.44577757e-01,  8.55868773e-01,  4.22460141e-01,
         8.01380844e-02,  1.22545781e+00],
       [-9.23530083e-01, -4.48000209e-01,  2.74653778e-01,
         2.67783910e+00, -9.04377163e-01],
       [ 9.00613703e-01,  1.67078689e+00,  1.46737783e+00,
         8.04589933e-01,  1.22545781e+00],
       [-9.23530083e-01, -1.09993470e+00, -5.82486372e-01,
         4.77166686e-01, -9.04377163e-01],
       [-9.23530083e-01, -1.09993470e+00, -1.27784912e+00,
        -1.30814884e+00,  1.60540325e-01],
       [-9.23530083e-01, -9.36951078e-01, -1.29756904e-01,
         1.63953115e+00,  1.60540325e-01],
       [ 9.00613703e-01,  1.67078689e+00,  1.39736947e+00,
         7.27556959e-01,  1.22545781e+00],
       [ 9.00613703e-01,  1.01885240e+00,  1.18185773e+00,
         4.90420836e-01,  1.22545781e+00],
       [ 9.00613703e-01,  4.09506590e-02, -3.26450961e-01,
        -1.16923107e+00,  1.60540325e-01],
       [-1.14581896e-02, -1.22032964e-01,  2.09853105e-01,
         3.48059709e-01,  1.22545781e+00],
       [ 1.35664965e+00,  6.92885150e-01, -6.30083085e-01,
        -1.67754457e+00,  1.60540325e-01],
       [-9.23530083e-01, -7.73967455e-01, -2.17981221e-01,
         1.41301881e+00, -9.04377163e-01],
       [ 9.00613703e-01,  5.29901527e-01,  1.22110135e+00,
         5.33602158e-01,  1.22545781e+00],
       [-4.67494136e-01, -4.48000209e-01, -5.35704728e-01,
        -2.76304950e-01, -9.04377163e-01],
       [ 4.44577757e-01,  8.55868773e-01,  1.01153031e+00,
         8.36344918e-01,  1.22545781e+00],
       [ 1.35664965e+00,  1.83377051e+00,  2.50159022e+00,
         1.33762179e+00,  1.22545781e+00],
       [-1.14581896e-02, -1.22032964e-01, -3.33485712e-01,
        -4.88940458e-01,  1.22545781e+00],
       [-1.14581896e-02, -1.22032964e-01, -1.55560110e-01,
        -2.14850417e-01,  1.60540325e-01],
       [ 4.44577757e-01,  5.29901527e-01,  5.84817389e-01,
         2.88560895e-01,  1.22545781e+00],
       [-1.83560198e+00, -1.91485281e+00, -1.67990212e+00,
        -1.22711113e+00, -1.96929465e+00],
       [ 1.35664965e+00,  1.34481964e+00,  1.97255613e+00,
         8.28269237e-01,  1.22545781e+00],
       [-1.83560198e+00, -1.75186919e+00, -1.85165727e+00,
        -2.55003420e+00, -1.96929465e+00],
       [-9.23530083e-01, -1.09993470e+00, -7.27026992e-01,
         1.06064534e-01, -9.04377163e-01],
       [-9.23530083e-01, -7.73967455e-01, -9.99839684e-01,
        -5.94370940e-01, -9.04377163e-01],
       [-1.37956603e+00, -1.26291832e+00, -1.14281581e+00,
         6.34039835e-03, -1.96929465e+00],
       [-1.14581896e-02,  4.09506590e-02,  3.13147981e-01,
         5.07182941e-01,  1.60540325e-01],
       [ 2.26872154e+00,  2.32272138e+00,  2.29553108e+00,
         3.31972951e-01,  1.60540325e-01],
       [-9.23530083e-01, -6.10983832e-01,  1.81593753e-01,
         2.43891128e+00, -9.04377163e-01],
       [ 4.44577757e-01,  2.03934282e-01,  3.41084587e-01,
        -2.43261251e-02,  1.22545781e+00],
       [ 1.35664965e+00,  1.50780326e+00,  1.35832277e+00,
         2.36887066e-01, -9.04377163e-01],
       [-1.14581896e-02, -4.48000209e-01, -3.21992700e-01,
        -4.71235755e-01, -9.04377163e-01],
       [-4.67494136e-01, -1.22032964e-01, -1.86986740e-01,
         3.95184472e-01, -9.04377163e-01],
       [-9.23530083e-01, -9.36951078e-01, -1.13042021e+00,
        -9.29631110e-01, -9.04377163e-01],
       [-1.14581896e-02,  4.09506590e-02, -2.55857285e-01,
        -3.69355763e-01, -9.04377163e-01],
       [-9.23530083e-01, -4.48000209e-01, -7.69541835e-01,
        -3.09059340e-03, -9.04377163e-01],
       [-9.23530083e-01, -7.73967455e-01, -2.25426241e-01,
         1.39390403e+00,  1.60540325e-01],
       [ 1.81268560e+00,  2.48570500e+00,  1.30282700e+00,
        -1.58822507e-01,  1.22545781e+00],
       [-1.14581896e-02, -2.85016587e-01, -6.20466372e-01,
        -9.31027150e-01,  1.60540325e-01],
       [-9.23530083e-01, -9.36951078e-01, -1.43868564e+00,
        -1.72109005e+00, -9.04377163e-01],
       [-1.83560198e+00, -1.75186919e+00, -1.35213522e+00,
         1.29747337e+00, -1.96929465e+00],
       [-4.67494136e-01, -1.22032964e-01,  4.29002569e-01,
         1.58133007e+00,  1.60540325e-01],
       [-1.83560198e+00, -1.58888557e+00, -1.34557091e+00,
         1.34803416e+00, -1.96929465e+00],
       [ 4.44577757e-01,  2.03934282e-01,  4.11175356e-02,
        -4.09402718e-01,  1.22545781e+00],
       [ 9.00613703e-01,  1.67078689e+00,  2.24586661e+00,
         1.66119204e+00,  1.22545781e+00],
       [-9.23530083e-01, -1.42590195e+00, -1.54508215e+00,
        -1.99425876e+00, -9.04377163e-01],
       [ 1.81268560e+00,  1.18183602e+00,  5.32685833e-01,
        -8.17924536e-01,  1.60540325e-01],
       [-9.23530083e-01, -9.36951078e-01, -4.75356845e-01,
         7.52217382e-01,  1.60540325e-01],
       [-1.14581896e-02,  4.09506590e-02, -3.89829366e-01,
        -5.75736480e-01,  1.22545781e+00],
       [ 9.00613703e-01,  1.50780326e+00,  1.71597369e+00,
         1.07812983e+00,  1.60540325e-01],
       [-1.14581896e-02, -4.48000209e-01, -7.28602426e-01,
        -1.09760810e+00,  1.60540325e-01],
       [-1.37956603e+00, -9.36951078e-01, -4.98392101e-01,
         2.48813783e+00, -1.96929465e+00],
       [ 9.00613703e-01,  5.29901527e-01,  3.66969847e-01,
        -4.06232636e-01,  1.22545781e+00],
       [ 4.44577757e-01,  1.18183602e+00, -1.80329437e-01,
        -6.93680758e-01,  1.60540325e-01],
       [-4.67494136e-01, -4.48000209e-01, -2.46907943e-01,
         2.79800536e-01, -9.04377163e-01],
       [ 1.81268560e+00,  1.01885240e+00,  9.99785669e-01,
        -4.18171269e-01,  1.22545781e+00],
       [-4.67494136e-01, -6.10983832e-01, -1.25834765e+00,
        -1.66782215e+00,  1.60540325e-01],
       [-1.37956603e+00, -1.26291832e+00, -1.19418153e+00,
        -1.91478692e-01, -9.04377163e-01],
       [-1.14581896e-02,  5.29901527e-01,  1.42533343e+00,
         2.22047744e+00,  1.60540325e-01],
       [-1.83560198e+00, -1.91485281e+00, -1.82147239e+00,
        -2.31753883e+00, -1.96929465e+00],
       [ 1.35664965e+00,  2.03934282e-01, -1.69191992e-01,
        -1.23379991e+00,  1.22545781e+00],
       [ 1.35664965e+00,  1.34481964e+00,  1.77696159e+00,
         6.39951362e-01,  1.60540325e-01],
       [ 4.44577757e-01,  2.03934282e-01,  8.40305775e-01,
         6.16538907e-01,  1.22545781e+00],
       [ 1.35664965e+00,  1.18183602e+00,  1.13982427e+00,
         2.65173135e-02,  1.60540325e-01],
       [ 1.35664965e+00,  1.34481964e+00,  1.45784864e+00,
         3.32710296e-01,  1.22545781e+00],
       [-1.14581896e-02, -9.36951078e-01, -5.49632005e-01,
        -8.21908539e-01,  1.60540325e-01],
       [ 1.35664965e+00,  1.34481964e+00,  1.70222693e+00,
         5.67997038e-01,  1.22545781e+00],
       [ 4.44577757e-01,  5.29901527e-01,  7.33088724e-01,
         4.78901202e-01,  1.60540325e-01],
       [-1.14581896e-02,  4.09506590e-02, -2.88837469e-01,
        -4.20160930e-01,  1.60540325e-01],
       [-1.14581896e-02, -1.22032964e-01,  8.56673144e-02,
         1.56754534e-01,  1.60540325e-01],
       [ 9.00613703e-01,  5.29901527e-01,  7.55566013e-01,
         2.13551472e-02,  1.60540325e-01],
       [ 2.72475749e+00,  3.13763949e+00,  1.10495684e+00,
        -7.95233892e-01,  1.22545781e+00],
       [-1.83560198e+00, -1.42590195e+00, -1.38123699e+00,
         1.07332053e+00, -1.96929465e+00],
       [-1.14581896e-02,  5.29901527e-01, -8.17417530e-01,
        -1.23442560e+00,  1.22545781e+00],
       [-9.23530083e-01, -7.73967455e-01, -8.24807848e-01,
        -1.44983832e-01, -9.04377163e-01],
       [ 1.35664965e+00,  1.50780326e+00,  7.35632394e-01,
        -3.62637498e-01,  1.22545781e+00],
       [-1.14581896e-02,  8.55868773e-01,  1.26533386e+00,
         1.97400201e+00,  1.22545781e+00],
       [-9.23530083e-01, -7.73967455e-01, -1.80592009e-01,
         1.50901409e+00, -9.04377163e-01],
       [ 4.44577757e-01, -2.85016587e-01, -3.87641263e-01,
        -9.59813093e-01,  1.22545781e+00],
       [-4.67494136e-01, -1.22032964e-01,  3.06857185e-01,
         1.34612759e+00,  1.22545781e+00],
       [ 4.44577757e-01, -4.48000209e-01, -1.78026101e-02,
        -4.85040255e-01,  1.22545781e+00],
       [-1.14581896e-02, -1.09993470e+00, -1.24486894e+00,
        -1.89290404e+00,  1.60540325e-01],
       [-9.23530083e-01, -6.10983832e-01, -5.45545722e-01,
         5.72010301e-01, -1.96929465e+00],
       [-4.67494136e-01, -7.73967455e-01, -1.36362276e+00,
        -1.87053932e+00,  1.60540325e-01],
       [ 9.00613703e-01,  6.92885150e-01,  8.78105256e-01,
         1.56189939e-01,  1.22545781e+00],
       [-1.37956603e+00, -1.42590195e+00, -1.13084142e+00,
         5.24560520e-02, -9.04377163e-01],
       [ 9.00613703e-01,  1.01885240e+00,  4.35988088e-01,
        -3.30289126e-01,  1.60540325e-01],
       [-4.67494136e-01, -4.48000209e-01, -2.69877555e-01,
         2.35570379e-01, -9.04377163e-01],
       [ 4.44577757e-01,  4.09506590e-02,  6.00774131e-01,
         3.09045038e-01,  1.60540325e-01],
       [ 4.44577757e-01, -2.85016587e-01, -1.28241643e-01,
        -6.26814114e-01,  1.60540325e-01],
       [-1.37956603e+00, -1.58888557e+00, -1.47375546e+00,
        -1.26817071e+00, -1.96929465e+00],
       [-9.23530083e-01, -6.10983832e-01, -6.16883353e-01,
         3.88853840e-01,  1.60540325e-01],
       [-1.83560198e+00, -1.75186919e+00, -1.56775090e+00,
        -3.63280042e-01, -1.96929465e+00],
       [-9.23530083e-01, -9.36951078e-01, -8.33390682e-01,
        -1.67019909e-01, -9.04377163e-01],
       [-9.23530083e-01, -7.73967455e-01, -8.84023388e-01,
        -2.97017318e-01, -9.04377163e-01],
       [-4.67494136e-01, -2.85016587e-01, -3.18907475e-01,
         1.41158638e-01, -9.04377163e-01],
       [-1.14581896e-02,  5.29901527e-01, -4.31075109e-01,
        -6.39274539e-01, -9.04377163e-01],
       [-4.67494136e-01, -4.48000209e-01, -1.81467250e-01,
         4.05812771e-01,  1.60540325e-01],
       [ 4.44577757e-01,  1.34481964e+00,  4.54948001e-01,
         1.21843714e-01, -9.04377163e-01],
       [-1.14581896e-02, -2.85016587e-01, -7.37195843e-02,
        -8.87770874e-02, -9.04377163e-01],
       [-1.14581896e-02,  6.92885150e-01,  1.17224101e+00,
         1.83059476e+00,  1.60540325e-01],
       [ 1.35664965e+00,  4.09506590e-02,  1.29276209e-01,
        -9.46435550e-01,  1.60540325e-01],
       [-1.37956603e+00, -1.26291832e+00, -8.63849077e-01,
         1.08069398e+00, -9.04377163e-01],
       [ 2.26872154e+00,  2.32272138e+00,  3.94217164e+00,
         1.60027772e+00,  1.22545781e+00],
       [-4.67494136e-01, -2.85016587e-01, -6.71897735e-01,
        -5.38557446e-01, -9.04377163e-01],
       [ 9.00613703e-01,  1.34481964e+00,  1.40985807e+00,
         7.41298659e-01,  1.22545781e+00],
       [-1.37956603e+00, -7.73967455e-01, -1.18301673e+00,
        -1.48480953e-01, -9.04377163e-01],
       [ 1.35664965e+00,  1.18183602e+00,  1.26032310e+00,
         1.42533259e-01,  1.22545781e+00],
       [-4.67494136e-01, -7.73967455e-01, -4.90416465e-01,
        -1.89098121e-01,  1.60540325e-01],
       [ 1.81268560e+00,  2.03934282e-01, -2.83837653e-01,
        -1.51672147e+00,  1.22545781e+00],
       [-1.14581896e-02,  8.55868773e-01,  1.08884146e+00,
         1.70211979e+00,  1.60540325e-01],
       [-1.14581896e-02,  3.66917905e-01,  5.12817857e-01,
         8.14769506e-01,  1.60540325e-01],
       [-1.83560198e+00, -1.75186919e+00, -1.57924938e+00,
        -4.51845692e-01, -1.96929465e+00],
       [-1.83560198e+00, -1.42590195e+00, -1.77419842e+00,
        -1.95341688e+00, -1.96929465e+00],
       [-1.14581896e-02, -4.48000209e-01, -4.45576405e-02,
        -4.38538257e-02,  1.60540325e-01],
       [ 4.44577757e-01,  6.92885150e-01,  6.98812090e-01,
         4.34899270e-01, -9.04377163e-01],
       [ 4.44577757e-01, -2.85016587e-01,  1.29259798e-01,
        -2.96251884e-01,  1.22545781e+00],
       [ 9.00613703e-01,  6.92885150e-01,  1.04510128e+00,
         3.39942295e-01,  1.60540325e-01],
       [ 2.72475749e+00,  2.48570500e+00,  2.27953058e+00,
         2.72216215e-02,  1.60540325e-01],
       [-1.14581896e-02, -4.48000209e-01, -8.70435268e-01,
        -1.31609812e+00,  1.60540325e-01],
       [-4.67494136e-01, -6.10983832e-01,  1.36321901e-01,
         1.01774580e+00,  1.60540325e-01],
       [-9.23530083e-01, -7.73967455e-01, -7.63048639e-01,
         1.35804225e-02, -9.04377163e-01],
       [-1.14581896e-02,  2.03934282e-01, -2.95604177e-01,
        -4.30584880e-01, -9.04377163e-01],
       [ 1.35664965e+00,  2.03934282e-01, -1.78048339e-01,
        -1.24232677e+00,  1.22545781e+00],
       [ 1.35664965e+00,  1.18183602e+00,  7.30238720e-01,
        -3.67830513e-01,  1.22545781e+00],
       [ 4.44577757e-01,  1.01885240e+00,  1.26251668e+00,
         1.15854355e+00, -9.04377163e-01],
       [-1.14581896e-02, -4.48000209e-01, -2.07664314e-01,
        -2.95115670e-01,  1.22545781e+00],
       [ 1.81268560e+00,  2.81167225e+00,  1.77279325e+00,
         2.43383893e-01,  1.60540325e-01],
       [-4.67494136e-01, -2.85016587e-01, -5.80921879e-01,
        -3.63374843e-01,  1.60540325e-01],
       [-9.23530083e-01, -7.73967455e-01, -6.38321293e-01,
         3.33812802e-01,  1.60540325e-01],
       [-4.67494136e-01, -1.22032964e-01,  8.67864934e-01,
         2.42640100e+00, -9.04377163e-01],
       [ 4.44577757e-01,  1.18183602e+00,  5.83132550e-01,
         2.86398017e-01,  1.22545781e+00],
       [-1.14581896e-02,  3.66917905e-01,  8.01078557e-01,
         1.25882807e+00,  1.22545781e+00],
       [-1.14581896e-02,  3.66917905e-01,  9.17928732e-01,
         1.43883291e+00, -1.96929465e+00],
       [ 4.44577757e-01, -4.48000209e-01, -6.92323677e-01,
        -1.35094294e+00,  1.60540325e-01],
       [ 1.35664965e+00,  1.18183602e+00,  1.28043724e+00,
         1.61899095e-01,  1.22545781e+00],
       [-1.14581896e-02, -1.22032964e-01, -3.14739139e-01,
        -4.60061820e-01,  1.60540325e-01],
       [ 2.26872154e+00,  2.15973776e+00,  1.50060964e+00,
        -2.80305572e-01,  1.22545781e+00],
       [-9.23530083e-01, -1.22032964e-01, -6.21418196e-01,
         3.77210813e-01, -9.04377163e-01],
       [-4.67494136e-01, -6.10983832e-01, -5.23779567e-01,
        -2.53341924e-01,  1.60540325e-01],
       [-4.67494136e-01, -6.10983832e-01, -4.14910498e-01,
        -4.37042500e-02,  1.60540325e-01],
       [ 4.44577757e-01,  2.03934282e-01,  1.01481829e-01,
        -3.31911285e-01,  1.22545781e+00],
       [ 4.44577757e-01,  3.66917905e-01, -6.54868465e-02,
        -5.46253922e-01,  1.22545781e+00],
       [-1.14581896e-02,  6.92885150e-01,  8.27899231e-01,
         1.30014466e+00,  1.22545781e+00],
       [-1.14581896e-02, -1.22032964e-01,  2.09459246e-01,
         3.47452980e-01,  1.60540325e-01],
       [ 9.00613703e-01, -2.85016587e-01, -4.05534119e-02,
        -8.54646650e-01,  1.22545781e+00],
       [-9.23530083e-01, -6.10983832e-01, -2.35190294e-02,
         1.91229257e+00,  1.60540325e-01],
       [-9.23530083e-01, -9.36951078e-01, -9.33047837e-01,
        -4.22885595e-01, -9.04377163e-01],
       [-1.14581896e-02, -2.85016587e-01,  6.26413229e-01,
         9.89760399e-01,  1.60540325e-01],
       [ 1.35664965e+00,  1.34481964e+00,  1.99336499e+00,
         8.48303950e-01,  1.22545781e+00],
       [-1.14581896e-02, -2.85016587e-01, -4.50806329e-01,
        -6.69670001e-01,  1.22545781e+00],
       [-1.14581896e-02,  2.03934282e-01, -2.64921502e-01,
        -3.83318968e-01,  1.22545781e+00],
       [-1.14581896e-02, -2.85016587e-01, -2.56743467e-01,
        -3.70720905e-01, -9.04377163e-01],
       [-4.67494136e-01, -7.73967455e-01, -7.62879061e-01,
        -7.13750583e-01,  1.60540325e-01],
       [-4.67494136e-01, -2.85016587e-01, -2.50551135e-01,
         2.72785227e-01, -1.96929465e+00],
       [ 9.00613703e-01,  2.03934282e-01,  2.19825385e-01,
        -5.68141527e-01,  1.22545781e+00],
       [ 4.44577757e-01,  6.92885150e-01,  3.11233391e-01,
        -6.26469903e-02,  1.60540325e-01],
       [-4.67494136e-01, -1.22032964e-01,  8.29053455e-01,
         2.35166583e+00,  1.60540325e-01],
       [-9.23530083e-01, -6.10983832e-01, -8.41689063e-01,
        -1.88325664e-01, -9.04377163e-01],

In [28]:
from sklearn.metrics.pairwise import cosine_similarity

In [29]:
similarity_matrix=cosine_similarity(scaled)

In [30]:
similarity_matrix

array([[ 1.        ,  0.09180704,  0.22156969, ...,  0.34176742,
         0.11421506,  0.02495034],
       [ 0.09180704,  1.        ,  0.31812628, ...,  0.88603258,
         0.9922126 , -0.94217846],
       [ 0.22156969,  0.31812628,  1.        , ...,  0.40059553,
         0.27058876, -0.00457362],
       ...,
       [ 0.34176742,  0.88603258,  0.40059553, ...,  1.        ,
         0.92191208, -0.74307215],
       [ 0.11421506,  0.9922126 ,  0.27058876, ...,  0.92191208,
         1.        , -0.93692571],
       [ 0.02495034, -0.94217846, -0.00457362, ..., -0.74307215,
        -0.93692571,  1.        ]])

In [31]:
lookalike_results = {}
for idx, customer_id in enumerate(customer_features['CustomerID']):
    # Get similarity scores for the current customer
    scores = list(enumerate(similarity_matrix[idx]))
    # Sort by score (highest to lowest) and exclude self
    top_lookalikes = sorted(scores, key=lambda x: x[1], reverse=True)[1:4]
    # Store results
    lookalike_results[customer_id] = [
        (customer_features['CustomerID'][i], score) for i, score in top_lookalikes
    ]

In [32]:
lookalike_results

{'C0001': [('C0164', 0.9461036547290986),
  ('C0189', 0.9212019961927622),
  ('C0056', 0.8825391861811839)],
 'C0002': [('C0199', 0.9922126048410694),
  ('C0010', 0.9784392233423558),
  ('C0142', 0.9752729349685342)],
 'C0003': [('C0027', 0.8593960251505658),
  ('C0166', 0.7203628292991985),
  ('C0036', 0.6470289039642599)],
 'C0004': [('C0165', 0.9895420460802031),
  ('C0156', 0.9846938836563774),
  ('C0195', 0.9841600090625802)],
 'C0005': [('C0131', 0.9972501180161066),
  ('C0159', 0.9963804985451794),
  ('C0130', 0.9953131108474632)],
 'C0006': [('C0079', 0.9999816433671646),
  ('C0196', 0.9916950274492897),
  ('C0026', 0.9543496593660685)],
 'C0007': [('C0080', 0.9942236748416815),
  ('C0078', 0.993001261262817),
  ('C0110', 0.9856174424158116)],
 'C0008': [('C0093', 0.9491673290554926),
  ('C0162', 0.9377723876610214),
  ('C0084', 0.9352068194472882)],
 'C0009': [('C0083', 0.992909662092656),
  ('C0097', 0.9772633162341084),
  ('C0077', 0.9766013726794228)],
 'C0010': [('C0002', 0.9784392233423558),
  ('C0142', 0.9503617602999063),
  ('C0199', 0.9453581461597368)],
 'C0011': [('C0170', 0.9822858217687888),
  ('C0114', 0.9807639821751828),
  ('C0064', 0.9671913841284322)],
 'C0012': [('C0065', 0.9954934155564871),
  ('C0099', 0.9857385121959003),
  ('C0101', 0.9833735330438357)],
 'C0013': [('C0105', 0.9924388129281112),
  ('C0099', 0.9880826624132011),
  ('C0141', 0.9865984502070573)],
 'C0014': [('C0058', 0.9957297878663919),
  ('C0128', 0.9948333917280976),
  ('C0151', 0.991750004853011)],
 'C0015': [('C0095', 0.9936747017012335),
  ('C0186', 0.988079315686734),
  ('C0198', 0.986746713307453)],
 'C0016': [('C0107', 0.9094690732552526),
  ('C0183', 0.8772167548693839),
  ('C0158', 0.8554428393455118)],
 'C0017': [('C0113', 0.9984532033860958),
  ('C0162', 0.9981238634600286),
  ('C0093', 0.972837703141096)],
 'C0018': [('C0148', 0.9857744891327612),
  ('C0149', 0.978193471778759),
  ('C0138', 0.9663514761272778)],
 'C0019': [('C0038', 0.890878428400554),
  ('C0010', 0.8493068292376531),
  ('C0069', 0.8403128320243626)],
 'C0020': [('C0110', 0.9987496444700448),
  ('C0078', 0.9962793394565665),
  ('C0080', 0.9953572524957549)],
 'C0021': [('C0145', 0.9799215043027268),
  ('C0122', 0.9796192971082974),
  ('C0173', 0.9792150877625683)],
 'C0022': [('C0057', 0.9921437227864249),
  ('C0100', 0.9798663111700106),
  ('C0051', 0.9548032280244274)],
 'C0023': [('C0163', 0.9263459304543009),
  ('C0153', 0.9202834618603327),
  ('C0171', 0.9108337546754878)],
 'C0024': [('C0194', 0.9934085688173274),
  ('C0098', 0.9645947636649768),
  ('C0161', 0.9636473713352381)],
 'C0025': [('C0032', 0.9968939622767461),
  ('C0029', 0.9894068485080162),
  ('C0121', 0.9876993859318582)],
 'C0026': [('C0185', 0.9810818366861362),
  ('C0006', 0.9543496593660685),
  ('C0079', 0.9525223320663145)],
 'C0027': [('C0166', 0.9714039124246732),
  ('C0036', 0.9245038831232457),
  ('C0035', 0.9221278697170329)],
 'C0028': [('C0104', 0.9922053275429895),
  ('C0045', 0.9898143558073208),
  ('C0041', 0.9895809003147872)],
 'C0029': [('C0031', 0.9951230778778815),
  ('C0094', 0.9904640714720441),
  ('C0025', 0.9894068485080162)],
 'C0030': [('C0106', 0.9911524890676666),
  ('C0174', 0.9630537767797599),
  ('C0076', 0.9571970120332578)],
 'C0031': [('C0029', 0.9951230778778815),
  ('C0025', 0.9874679097193938),
  ('C0032', 0.9866632348737484)],
 'C0032': [('C0025', 0.9968939622767461),
  ('C0043', 0.9899487054975333),
  ('C0031', 0.9866632348737484)],
 'C0033': [('C0097', 0.9993832726645439),
  ('C0060', 0.99925729082339),
  ('C0151', 0.9960165984743801)],
 'C0034': [('C0091', 0.9583702293173976),
  ('C0049', 0.9257259072697965),
  ('C0047', 0.802331102146676)],
 'C0035': [('C0036', 0.9941879546400099),
  ('C0177', 0.9901683357956729),
  ('C0178', 0.9700307957657696)],
 'C0036': [('C0035', 0.9941879546400099),
  ('C0177', 0.9786094685393896),
  ('C0178', 0.9650260480575925)],
 'C0037': [('C0171', 0.9994890907595728),
  ('C0023', 0.9101250962876914),
  ('C0163', 0.8576232918125243)],
 'C0038': [('C0160', 0.9732447864480179),
  ('C0072', 0.9728739030337066),
  ('C0134', 0.9268780268043344)],
 'C0039': [('C0169', 0.9821976287192231),
  ('C0057', 0.9658006542002885),
  ('C0122', 0.9394011178323001)],
 'C0040': [('C0066', 0.9966408049329758),
  ('C0168', 0.9600716558256217),
  ('C0115', 0.9298954519915361)],
 'C0041': [('C0045', 0.9995119425538627),
  ('C0143', 0.9958552077421045),
  ('C0028', 0.9895809003147872)],
 'C0042': [('C0078', 0.9862645333274977),
  ('C0020', 0.9837803521673508),
  ('C0080', 0.9785190985752499)],
 'C0043': [('C0192', 0.992380469541093),
  ('C0032', 0.9899487054975333),
  ('C0031', 0.9866448779475965)],
 'C0044': [('C0074', 0.9956756233130937),
  ('C0158', 0.9815781838678884),
  ('C0185', 0.9806383646938306)],
 'C0045': [('C0041', 0.9995119425538627),
  ('C0143', 0.9946283731033447),
  ('C0028', 0.9898143558073208)],
 'C0046': [('C0143', 0.991257439115459),
  ('C0104', 0.9879567852123307),
  ('C0102', 0.9851249649132668)],
 'C0047': [('C0049', 0.9604902535905294),
  ('C0127', 0.925569465614277),
  ('C0139', 0.9124979797891593)],
 'C0048': [('C0067', 0.8682672764324671),
  ('C0022', 0.8559057006747215),
  ('C0100', 0.8541928001123389)],
 'C0049': [('C0047', 0.9604902535905294),
  ('C0034', 0.9257259072697965),
  ('C0147', 0.8720858385277983)],
 'C0050': [('C0115', 0.9992523597408741),
  ('C0089', 0.9850460166676593),
  ('C0066', 0.9432955178359034)],
 'C0051': [('C0046', 0.9762242439137536),
  ('C0122', 0.9686560550375816),
  ('C0059', 0.9642979380933004)],
 'C0052': [('C0128', 0.972606197992279),
  ('C0142', 0.9697959518644589),
  ('C0063', 0.9663199317480197)],
 'C0053': [('C0143', 0.969502450020564),
  ('C0046', 0.9620940360112098),
  ('C0041', 0.9578695804751785)],
 'C0054': [('C0188', 0.9899551648763727),
  ('C0059', 0.9892634657382428),
  ('C0141', 0.9882895289834207)],
 'C0055': [('C0086', 0.9908091388342274),
  ('C0189', 0.9861767857312563),
  ('C0190', 0.9667548714163053)],
 'C0056': [('C0174', 0.9541304742974767),
  ('C0088', 0.9201616166009149),
  ('C0076', 0.9191610197703486)],
 'C0057': [('C0022', 0.9921437227864249),
  ('C0039', 0.9658006542002885),
  ('C0122', 0.9625284223715439)],
 'C0058': [('C0014', 0.9957297878663919),
  ('C0128', 0.9935326340924449),
  ('C0186', 0.993400741309198)],
 'C0059': [('C0188', 0.9999749661663466),
  ('C0104', 0.995019358582963),
  ('C0054', 0.9892634657382428)],
 'C0060': [('C0033', 0.99925729082339),
  ('C0097', 0.9980848690445354),
  ('C0151', 0.9931647232189491)],
 'C0061': [('C0005', 0.9929820890360813),
  ('C0123', 0.9877525743221122),
  ('C0159', 0.9855423639326765)],
 'C0062': [('C0186', 0.991636732252256),
  ('C0014', 0.9915832323841359),
  ('C0058', 0.9914284526533295)],
 'C0063': [('C0159', 0.9855812599504848),
  ('C0130', 0.9836120275189126),
  ('C0150', 0.9806914061784637)],
 'C0064': [('C0096', 0.971156911589713),
  ('C0011', 0.9671913841284322),
  ('C0138', 0.953764396216952)],
 'C0065': [('C0012', 0.9954934155564871),
  ('C0156', 0.9939880108448623),
  ('C0101', 0.9933925739021467)],
 'C0066': [('C0040', 0.9966408049329758),
  ('C0115', 0.955272005802421),
  ('C0050', 0.9432955178359034)],
 'C0067': [('C0179', 0.9591283716575942),
  ('C0057', 0.9460155102047786),
  ('C0022', 0.941961406533833)],
 'C0068': [('C0065', 0.92266541101493),
  ('C0156', 0.9171439235796138),
  ('C0153', 0.9129534351426469)],
 'C0069': [('C0191', 0.9881144037132503),
  ('C0137', 0.9129843283777188),
  ('C0199', 0.9088342188898828)],
 'C0070': [('C0120', 0.9802590036937758),
  ('C0133', 0.9562839396024193),
  ('C0092', 0.9542213868987878)],
 'C0071': [('C0014', 0.991632648708159),
  ('C0062', 0.989431483149554),
  ('C0151', 0.989071824411317)],
 'C0072': [('C0160', 0.9865000680487415),
  ('C0038', 0.9728739030337066),
  ('C0191', 0.9506697057656662)],
 'C0073': [('C0197', 0.9893053104576359),
  ('C0159', 0.9825800462135126),
  ('C0112', 0.9804659890875801)],
 'C0074': [('C0044', 0.9956756233130937),
  ('C0185', 0.9743496688703845),
  ('C0158', 0.9622615303600565)],
 'C0075': [('C0175', 0.9866699966149755),
  ('C0195', 0.9830083522939994),
  ('C0109', 0.9770612990060532)],
 'C0076': [('C0157', 0.998801582729572),
  ('C0088', 0.9967073552921505),
  ('C0174', 0.9900962006793996)],
 'C0077': [('C0083', 0.9914833844007683),
  ('C0060', 0.982341343379396),
  ('C0033', 0.9775525679728122)],
 'C0078': [('C0080', 0.9990526221285486),
  ('C0020', 0.9962793394565665),
  ('C0110', 0.9955974832316359)],
 'C0079': [('C0006', 0.9999816433671646),
  ('C0196', 0.9924560969971568),
  ('C0026', 0.9525223320663145)],
 'C0080': [('C0078', 0.9990526221285486),
  ('C0110', 0.9968311744666266),
  ('C0020', 0.9953572524957549)],
 'C0081': [('C0179', 0.9975254476789909),
  ('C0181', 0.9875471683236094),
  ('C0194', 0.9577407183452256)],
 'C0082': [('C0054', 0.9875692166074087),
  ('C0105', 0.968905524858103),
  ('C0143', 0.9662072437661514)],
 'C0083': [('C0009', 0.992909662092656),
  ('C0077', 0.9914833844007683),
  ('C0060', 0.9749645147971594)],
 'C0084': [('C0124', 0.9591131183958591),
  ('C0008', 0.9352068194472882),
  ('C0109', 0.9331570589204801)],
 'C0085': [('C0135', 0.9914627058609262),
  ('C0167', 0.9568714908807558),
  ('C0129', 0.9553700497035857)],
 'C0086': [('C0055', 0.9908091388342274),
  ('C0190', 0.9806603205596152),
  ('C0189', 0.9735396300655301)],
 'C0087': [('C0105', 0.9903353730784258),
  ('C0013', 0.9818534689391941),
  ('C0099', 0.9702451498581164)],
 'C0088': [('C0157', 0.9985553898482779),
  ('C0076', 0.9967073552921505),
  ('C0119', 0.991039806968465)],
 'C0089': [('C0050', 0.9850460166676593),
  ('C0115', 0.9844879270300294),
  ('C0066', 0.9368531774246079)],
 'C0090': [('C0194', 0.9730049006689171),
  ('C0162', 0.9524057063993381),
  ('C0024', 0.9515959565055433)],
 'C0091': [('C0034', 0.9583702293173976),
  ('C0124', 0.826768734879643),
  ('C0109', 0.824344459746173)],
 'C0092': [('C0125', 0.9991020171697381),
  ('C0120', 0.9904077777094702),
  ('C0133', 0.98186376173825)],
 'C0093': [('C0162', 0.9831698759001798),
  ('C0021', 0.9757707960052048),
  ('C0017', 0.972837703141096)],
 'C0094': [('C0121', 0.9989109264361483),
  ('C0029', 0.9904640714720441),
  ('C0025', 0.9846656249478273)],
 'C0095': [('C0015', 0.9936747017012335),
  ('C0123', 0.9926105511225266),
  ('C0131', 0.9895783079689986)],
 'C0096': [('C0138', 0.9938828627098601),
  ('C0149', 0.9818854243160721),
  ('C0148', 0.9795720002992349)],
 'C0097': [('C0033', 0.9993832726645439),
  ('C0060', 0.9980848690445354),
  ('C0151', 0.9939419516713629)],
 'C0098': [('C0161', 0.9999877119936298),
  ('C0147', 0.992783619868175),
  ('C0024', 0.9645947636649768)],
 'C0099': [('C0155', 0.9948653147655255),
  ('C0013', 0.9880826624132011),
  ('C0012', 0.9857385121959003)],
 'C0100': [('C0022', 0.9798663111700106),
  ('C0051', 0.9574772392154429),
  ('C0057', 0.9497524186352921)],
 'C0101': [('C0156', 0.9990015118307385),
  ('C0065', 0.9933925739021467),
  ('C0108', 0.9854160778655267)],
 'C0102': [('C0173', 0.9962051979463683),
  ('C0145', 0.9954447857814399),
  ('C0104', 0.9946387603021714)],
 'C0103': [('C0119', 0.9523390223805531),
  ('C0192', 0.9236514250012349),
  ('C0025', 0.9204885109453845)],
 'C0104': [('C0059', 0.995019358582963),
  ('C0102', 0.9946387603021714),
  ('C0188', 0.9942891197593732)],
 'C0105': [('C0013', 0.9924388129281112),
  ('C0087', 0.9903353730784258),
  ('C0141', 0.9842717839391774)],
 'C0106': [('C0030', 0.9911524890676666),
  ('C0174', 0.959712349988741),
  ('C0076', 0.9352534121021352)],
 'C0107': [('C0183', 0.9263686212776888),
  ('C0016', 0.9094690732552526),
  ('C0117', 0.8828819671563051)],
 'C0108': [('C0101', 0.9854160778655267),
  ('C0156', 0.9788863419445516),
  ('C0065', 0.9713658731374163)],
 'C0109': [('C0124', 0.9844197453627587),
  ('C0075', 0.9770612990060532),
  ('C0195', 0.9761831937845568)],
 'C0110': [('C0020', 0.9987496444700448),
  ('C0080', 0.9968311744666266),
  ('C0078', 0.9955974832316359)],
 'C0111': [('C0106', 0.9104503325824546),
  ('C0086', 0.9084309224427067),
  ('C0190', 0.8693371426260674)],
 'C0112': [('C0130', 0.9976380817409889),
  ('C0150', 0.9970656579356506),
  ('C0131', 0.9968064804296822)],
 'C0113': [('C0017', 0.9984532033860958),
  ('C0162', 0.9937326509961995),
  ('C0075', 0.9767383766621516)],
 'C0114': [('C0182', 0.9835011756088394),
  ('C0011', 0.9807639821751828),
  ('C0170', 0.9724214308407888)],
 'C0115': [('C0050', 0.9992523597408741),
  ('C0089', 0.9844879270300294),
  ('C0066', 0.955272005802421)],
 'C0116': [('C0189', 0.9487966284137892),
  ('C0184', 0.944203721290827),
  ('C0118', 0.9317215189672863)],
 'C0117': [('C0011', 0.9095269157098307),
  ('C0170', 0.9072594702018457),
  ('C0107', 0.8828819671563051)],
 'C0118': [('C0154', 0.9810573183217738),
  ('C0184', 0.9462830844235252),
  ('C0164', 0.9321407988105189)],
 'C0119': [('C0088', 0.991039806968465),
  ('C0157', 0.9841911457673049),
  ('C0076', 0.9769913030490269)],
 'C0120': [('C0133', 0.9913587541415533),
  ('C0092', 0.9904077777094702),
  ('C0125', 0.989796435444724)],
 'C0121': [('C0094', 0.9989109264361483),
  ('C0025', 0.9876993859318582),
  ('C0029', 0.9868023357282318)],
 'C0122': [('C0021', 0.9796192971082974),
  ('C0145', 0.9787857208636991),
  ('C0173', 0.9787356546685125)],
 'C0123': [('C0095', 0.9926105511225266),
  ('C0061', 0.9877525743221122),
  ('C0005', 0.9866689143710361)],
 'C0124': [('C0109', 0.9844197453627587),
  ('C0195', 0.9743905036048934),
  ('C0004', 0.970509449978696)],
 'C0125': [('C0092', 0.9991020171697381),
  ('C0120', 0.989796435444724),
  ('C0133', 0.9866151870271661)],
 'C0126': [('C0141', 0.9185245077976187),
  ('C0013', 0.9172771228915207),
  ('C0155', 0.9052450543182754)],
 'C0127': [('C0047', 0.925569465614277),
  ('C0172', 0.9218549624243468),
  ('C0147', 0.8513221649618666)],
 'C0128': [('C0014', 0.9948333917280976),
  ('C0058', 0.9935326340924449),
  ('C0062', 0.9841371323901243)],
 'C0129': [('C0167', 0.9936265799272151),
  ('C0085', 0.9553700497035857),
  ('C0135', 0.9349269983296988)],
 'C0130': [('C0150', 0.9997010328971825),
  ('C0131', 0.9980435524285199),
  ('C0112', 0.9976380817409889)],
 'C0131': [('C0130', 0.9980435524285199),
  ('C0150', 0.997615113162981),
  ('C0005', 0.9972501180161066)],
 'C0132': [('C0112', 0.9960218399377216),
  ('C0186', 0.9956578394882102),
  ('C0150', 0.9953349902672348)],
 'C0133': [('C0120', 0.9913587541415533),
  ('C0125', 0.9866151870271661),
  ('C0092', 0.98186376173825)],
 'C0134': [('C0160', 0.9595859592552938),
  ('C0038', 0.9268780268043344),
  ('C0072', 0.9018371166493968)],
 'C0135': [('C0085', 0.9914627058609262),
  ('C0074', 0.9445631784567827),
  ('C0129', 0.9349269983296988)],
 'C0136': [('C0153', 0.901080307134736),
  ('C0068', 0.8977411463063452),
  ('C0165', 0.7964282298748252)],
 'C0137': [('C0191', 0.9481562036006935),
  ('C0193', 0.9382301474221786),
  ('C0069', 0.9129843283777188)],
 'C0138': [('C0148', 0.9957802584644777),
  ('C0149', 0.9948810313174256),
  ('C0096', 0.9938828627098601)],
 'C0139': [('C0047', 0.9124979797891593),
  ('C0147', 0.9074564163881199),
  ('C0049', 0.8651607898883266)],
 'C0140': [('C0007', 0.983140695102611),
  ('C0078', 0.979974942200339),
  ('C0080', 0.9783500042300218)],
 'C0141': [('C0054', 0.9882895289834207),
  ('C0013', 0.9865984502070573),
  ('C0105', 0.9842717839391774)],
 'C0142': [('C0002', 0.9752729349685342),
  ('C0199', 0.9739120634144537),
  ('C0052', 0.9697959518644589)],
 'C0143': [('C0041', 0.9958552077421045),
  ('C0045', 0.9946283731033447),
  ('C0046', 0.991257439115459)],
 'C0144': [('C0197', 0.9869697986170125),
  ('C0112', 0.9826393775581906),
  ('C0095', 0.9818703511320744)],
 'C0145': [('C0173', 0.9999488545131575),
  ('C0102', 0.9954447857814399),
  ('C0104', 0.9819509310581904)],
 'C0146': [('C0177', 0.9877458621827311),
  ('C0178', 0.9866901589915112),
  ('C0035', 0.9667206123196497)],
 'C0147': [('C0161', 0.9929425898440735),
  ('C0098', 0.992783619868175),
  ('C0024', 0.930446626109923)],
 'C0148': [('C0149', 0.995979873800602),
  ('C0138', 0.9957802584644777),
  ('C0018', 0.9857744891327612)],
 'C0149': [('C0148', 0.995979873800602),
  ('C0138', 0.9948810313174256),
  ('C0096', 0.9818854243160721)],
 'C0150': [('C0130', 0.9997010328971825),
  ('C0131', 0.997615113162981),
  ('C0112', 0.9970656579356506)],
 'C0151': [('C0033', 0.9960165984743801),
  ('C0097', 0.9939419516713629),
  ('C0060', 0.9931647232189491)],
 'C0152': [('C0001', 0.8085579953311568),
  ('C0146', 0.8031313732020227),
  ('C0103', 0.7686392455776526)],
 'C0153': [('C0163', 0.9437223639948831),
  ('C0023', 0.9202834618603327),
  ('C0068', 0.9129534351426469)],
 'C0154': [('C0118', 0.9810573183217738),
  ('C0179', 0.935661850990624),
  ('C0081', 0.9316098616780824)],
 'C0155': [('C0099', 0.9948653147655255),
  ('C0013', 0.9820618412960209),
  ('C0012', 0.979668509361442)],
 'C0156': [('C0101', 0.9990015118307385),
  ('C0065', 0.9939880108448623),
  ('C0004', 0.9846938836563774)],
 'C0157': [('C0076', 0.998801582729572),
  ('C0088', 0.9985553898482779),
  ('C0119', 0.9841911457673049)],
 'C0158': [('C0044', 0.9815781838678884),
  ('C0185', 0.968160326947434),
  ('C0074', 0.9622615303600565)],
 'C0159': [('C0005', 0.9963804985451794),
  ('C0112', 0.9952349909779483),
  ('C0130', 0.9927676715578436)],
 'C0160': [('C0072', 0.9865000680487415),
  ('C0038', 0.9732447864480179),
  ('C0134', 0.9595859592552938)],
 'C0161': [('C0098', 0.9999877119936298),
  ('C0147', 0.9929425898440735),
  ('C0024', 0.9636473713352381)],
 'C0162': [('C0017', 0.9981238634600286),
  ('C0113', 0.9937326509961995),
  ('C0093', 0.9831698759001798)],
 'C0163': [('C0153', 0.9437223639948831),
  ('C0023', 0.9263459304543009),
  ('C0087', 0.8676709469166709)],
 'C0164': [('C0055', 0.9568895380160561),
  ('C0189', 0.949092015014492),
  ('C0001', 0.9461036547290986)],
 'C0165': [('C0004', 0.9895420460802031),
  ('C0012', 0.9786384415543994),
  ('C0065', 0.9772602893766017)],
 'C0166': [('C0027', 0.9714039124246732),
  ('C0031', 0.9647573383948161),
  ('C0043', 0.9568821343642789)],
 'C0167': [('C0129', 0.9936265799272151),
  ('C0085', 0.9568714908807558),
  ('C0178', 0.9390799901383011)],
 'C0168': [('C0040', 0.9600716558256217),
  ('C0066', 0.9417944583535249),
  ('C0196', 0.9228609064891816)],
 'C0169': [('C0039', 0.9821976287192231),
  ('C0045', 0.9484520075311489),
  ('C0057', 0.945073004411532)],
 'C0170': [('C0200', 0.9933742614268003),
  ('C0182', 0.9885724096472257),
  ('C0011', 0.9822858217687888)],
 'C0171': [('C0037', 0.9994890907595728),
  ('C0023', 0.9108337546754878),
  ('C0153', 0.849941380241963)],
 'C0172': [('C0157', 0.9557576226228253),
  ('C0088', 0.9545234592984766),
  ('C0076', 0.9533255681593711)],
 'C0173': [('C0145', 0.9999488545131575),
  ('C0102', 0.9962051979463683),
  ('C0104', 0.9837498974567276)],
 'C0174': [('C0076', 0.9900962006793996),
  ('C0157', 0.9824589372610584),
  ('C0088', 0.9811599553189635)],
 'C0175': [('C0075', 0.9866699966149755),
  ('C0113', 0.9761360958430741),
  ('C0109', 0.9741439645747197)],
 'C0176': [('C0073', 0.9430205458169045),
  ('C0110', 0.9399674502946972),
  ('C0133', 0.9271591678926728)],
 'C0177': [('C0035', 0.9901683357956729),
  ('C0146', 0.9877458621827311),
  ('C0036', 0.9786094685393896)],
 'C0178': [('C0146', 0.9866901589915112),
  ('C0177', 0.9723890649334348),
  ('C0035', 0.9700307957657696)],
 'C0179': [('C0081', 0.9975254476789909),
  ('C0181', 0.9772108244710013),
  ('C0067', 0.9591283716575942)],
 'C0181': [('C0081', 0.9875471683236094),
  ('C0179', 0.9772108244710013),
  ('C0024', 0.9532170494369449)],
 'C0182': [('C0200', 0.9959483266058635),
  ('C0170', 0.9885724096472257),
  ('C0114', 0.9835011756088394)],
 'C0183': [('C0187', 0.9720609504486443),
  ('C0064', 0.9368539072034179),
  ('C0107', 0.9263686212776888)],
 'C0184': [('C0024', 0.954968902753966),
  ('C0098', 0.948845411494018),
  ('C0161', 0.9484705112485253)],
 'C0185': [('C0026', 0.9810818366861362),
  ('C0044', 0.9806383646938306),
  ('C0074', 0.9743496688703845)],

In [33]:
lookalike_df = pd.DataFrame({
    "CustomerID": list(lookalike_results.keys())[:20],
    "Lookalikes": [lookalike_results[cust_id] for cust_id in list(lookalike_results.keys())[:20]]
})
lookalike_df.to_csv("Tushar_Lookalike.csv", index=False)

In [34]:
lookalike_df

   CustomerID                                         Lookalikes
0       C0001  [(C0164, 0.9461036547290986), (C0189, 0.921201...
1       C0002  [(C0199, 0.9922126048410694), (C0010, 0.978439...
2       C0003  [(C0027, 0.8593960251505658), (C0166, 0.720362...
3       C0004  [(C0165, 0.9895420460802031), (C0156, 0.984693...
4       C0005  [(C0131, 0.9972501180161066), (C0159, 0.996380...
5       C0006  [(C0079, 0.9999816433671646), (C0196, 0.991695...
6       C0007  [(C0080, 0.9942236748416815), (C0078, 0.993001...
7       C0008  [(C0093, 0.9491673290554926), (C0162, 0.937772...
8       C0009  [(C0083, 0.992909662092656), (C0097, 0.9772633...
9       C0010  [(C0002, 0.9784392233423558), (C0142, 0.950361...
10      C0011  [(C0170, 0.9822858217687888), (C0114, 0.980763...
11      C0012  [(C0065, 0.9954934155564871), (C0099, 0.985738...
12      C0013  [(C0105, 0.9924388129281112), (C0099, 0.988082...
13      C0014  [(C0058, 0.9957297878663919), (C0128, 0.994833...
14      C0015  [(C0095, 0.9936747017012335), (C0186, 0.988079...
15      C0016  [(C0107, 0.9094690732552526), (C0183, 0.877216...
16      C0017  [(C0113, 0.9984532033860958), (C0162, 0.998123...
17      C0018  [(C0148, 0.9857744891327612), (C0149, 0.978193...
18      C0019  [(C0038, 0.890878428400554), (C0010, 0.8493068...
19      C0020  [(C0110, 0.9987496444700448), (C0078, 0.996279...